# jig.properties

# 공통 패키지 접두어 생략
jig.omit.prefix=com.github.raonjena99.multi_currency_ledger_service

# DDD 계층별 아키텍처 식별 패턴 매핑
jig.pattern.domain=.*\.domain\..*
jig.pattern.presentation=.*\\.presentation\\..*
jig.pattern.application=.*\\.application\\..*
jig.pattern.infrastructure=.*\\.infrastructure\\..*

# 아키텍처 다이어그램 노이즈 제거
jig.pattern.ignore=.*\\.(dto|exception|config)\\..*