@startuml
title <size:24>MultiCurrencyLedgerServiceApplication</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("MultiCurrencyLedgerServiceApplication_boundary", "MultiCurrencyLedgerServiceApplication", $tags="") {
  Container_Boundary("MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication_boundary", "MultiCurrencyLedgerServiceApplication", $tags="") {
    Component(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
    Component(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Account, "Account", $techn="Module", $descr="", $tags="", $link="")
    Component(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Reconciliation, "Reconciliation", $techn="Module", $descr="", $tags="", $link="")
    Component(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Portfolio, "Portfolio", $techn="Module", $descr="", $tags="", $link="")
    Component(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Transaction, "Transaction", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Transaction, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Portfolio, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Account, "listens to", $techn="", $tags="", $link="")
Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Portfolio, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Portfolio, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Account, "uses", $techn="", $tags="", $link="")
Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Account, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Reconciliation, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Common, "depends on", $techn="", $tags="", $link="")
Rel(MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Transaction, MultiCurrencyLedgerServiceApplication.MultiCurrencyLedgerServiceApplication.Reconciliation, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml